********************************************************************************
Test case WV-00-000 started
Traceback (most recent call last):
  File "/home/wison/pythonpytestautomationweb/TestCasess/Test_Demo.py", line 44, in test_WV00000
    self.d.get(self.url1.webViewerUAT)
AttributeError: 'TestExampleOne' object has no attribute 'd'
Exception Occured in test case WV-00-000
********************************************************************************
********************************************************************************
Test case WV-00-000 started
Test case WV-00-000 passed
Total time taken by Test case WV-00-000 to finish: 0.14438652992248535 seconds
********************************************************************************
********************************************************************************
Test case WV-00-000 started
Test case WV-00-000 passed
Total time taken by Test case WV-00-000 to finish: 0.14078116416931152 seconds
********************************************************************************
Suite started at Thu Feb 27 12:05:13 2020
Suite ended at Thu Feb 27 12:05:25 2020
Total time taken by Test Suite to finish: 12.27861475944519 seconds
********************************************************************************
Test case WV-00-000 started
Test case WV-00-000 passed
Total time taken by Test case WV-00-000 to finish: 0.1639082431793213 seconds
********************************************************************************
